version: "3.9"
services:
  database:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: rinha
      POSTGRES_USER: rinha
      POSTGRES_DB: rinha
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: 1536M
    ports:
      - "5432:5432"
  migrations:
    build:
      context: migrations/
      dockerfile: Dockerfile
    command: -url=jdbc:postgresql://database:5432/rinha -user=rinha -password=rinha -connectRetries=60 migrate
    depends_on:
      - database
  api1:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: api1
    environment:
      - DATABASE_URL=postgres://rinha:rinha@database:5432/rinha?sslmode=disable
    depends_on:
      - database
    expose:
      - "3000"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
  api2:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: api2
    environment:
      - DATABASE_URL=postgres://rinha:rinha@database:5432/rinha?sslmode=disable
    depends_on:
      - database
    expose:
      - "3000"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
      - database
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: 512M
